#version: "3.4"
name: portfolio_front
services:
  portfolio_react_front:
    container_name: portfolio_react_front
    build: 
      dockerfile: ./docker/dockerfile/Dockerfile
      context: ../
    restart: on-failure
    platform: linux/arm64
    volumes:
      - ..:/var/www/html
      - /var/www/html/node_modules
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true