services:
  portfolio_react_front:
    container_name: portfolio_react_front
    image: portfolio_react_front_image
    build: 
      dockerfile: ./docker/dockerfile/Dockerfile.prod
      context: ../
    restart: on-failure
    networks:
      - radx
    expose:
      - 80

networks:
  radx:
    name: radx
    external: true