services:
  portfolio_react_front:
    container_name: portfolio_react_front
    build: 
      dockerfile: ./docker/dockerfile/Dockerfile
      context: ../
    restart: on-failure
    networks:
      - radx
    volumes:
      - ../src:/var/www/html/src
    expose:
      - 3000
    environment:
      - WATCHPACK_POLLING=true

networks:
  radx:
    name: radx
    external: true