#version: "3.4"
services:
  portfolio_react_front:
    container_name: portfolio_react_front
    build: 
      dockerfile: ./docker/dockerfile/Dockerfile.prod
      context: ../
    restart: on-failure
    volumes:
      - ..:/var/www/html
      - /var/www/html/node_modules
    networks:
      - radx
    #ports:
    #  - 3000:3000
    #expose:
    #  - 3000

  portfolio_nginx_front:
    container_name: portfolio_nginx_front
    image: nginx:latest
    restart: on-failure
    networks:
      - radx
    expose:
      - 80
    volumes:
      - ..:/var/www/html
      - /var/www/html/node_modules
      - ./logs:/var/log/nginx
      - ./config/nginx:/etc/nginx/conf.d

networks:
  radx:
    name: radx
    external: true