#version: "3.4"
services:
  portfolio_react_front:
    container_name: portfolio_react_front
    build: 
      dockerfile: ./docker/dockerfile/Dockerfile.prod
      context: ../
    restart: on-failure
    volumes:
      - ..:/var/www/html
      - /var/www/html/node_modules
    networks:
      - radx
    expose:
      - 3000

networks:
  radx:
    name: radx
    external: true